# Generated by Django 3.1.3 on 2021-01-07 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210101_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='watchlist_user',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchlist_user',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
